#!/usr/bin/env bash
# OpenMLC installer — one-shot setup for `docker compose up`.
# Usage:  curl -sSL https://raw.githubusercontent.com/inversifyai-cloud/OpenMLC/main/install.sh | bash
#         (or download and run with `bash install.sh`)

set -euo pipefail

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
DIM='\033[2m'
BOLD='\033[1m'
NC='\033[0m'

step()  { printf "${GREEN}▸${NC} %s\n" "$1"; }
warn()  { printf "${YELLOW}!${NC} %s\n" "$1"; }
fail()  { printf "${RED}✗${NC} %s\n" "$1" >&2; exit 1; }
ask()   { printf "${BOLD}?${NC} %s " "$1"; }

REPO_RAW="https://raw.githubusercontent.com/inversifyai-cloud/OpenMLC/main"
INSTALL_DIR="${OPENMLC_DIR:-$HOME/openmlc}"

# ─── Banner ───────────────────────────────────────────────────────────────────
cat <<'BANNER'
   ___                   __  __ _    ___
  / _ \ _ __  ___ _ _   |  \/  | |  / __|
 | (_) | '_ \/ -_) ' \  | |\/| | |_| (__
  \___/| .__/\___|_||_| |_|  |_|____\___|
       |_|

  self-hosted, byok ai chat — installer

BANNER

# ─── Pre-flight ───────────────────────────────────────────────────────────────
command -v docker >/dev/null 2>&1 \
  || fail "docker is not installed. install it first: https://docs.docker.com/get-docker/"

if ! docker compose version >/dev/null 2>&1; then
  command -v docker-compose >/dev/null 2>&1 \
    || fail "docker compose is not installed. install Docker Desktop or the compose plugin."
fi

if ! command -v openssl >/dev/null 2>&1; then
  fail "openssl is required to generate secrets. install it (brew install openssl / apt install openssl) and re-run."
fi

if ! command -v gh >/dev/null 2>&1; then
  fail "the GitHub CLI (gh) is required. install it from https://cli.github.com and re-run."
fi

step "docker + openssl + gh found"

# ─── GHCR auth via gh ─────────────────────────────────────────────────────────
echo
printf "${DIM}OpenMLC's container image lives in GitHub's registry (ghcr.io).${NC}\n"
printf "${DIM}We'll use the GitHub CLI to authenticate — no manual token needed.${NC}\n"
echo

if ! gh auth status >/dev/null 2>&1; then
  step "logging into GitHub…"
  gh auth login --git-protocol https --web --scopes read:packages \
    || fail "gh auth login failed. re-run and follow the prompts."
fi

GH_USER=$(gh api user -q .login 2>/dev/null) \
  || fail "could not get GitHub username. try 'gh auth status' to check your session."

# ensure token has read:packages scope — docker login succeeds without it but pull fails
SCOPES=$(gh api /user --include 2>/dev/null | grep -i "^x-oauth-scopes:" | cut -d' ' -f2-)
if ! echo "$SCOPES" | grep -q "read:packages"; then
  step "refreshing GitHub token with read:packages scope…"
  gh auth refresh -s read:packages \
    || fail "gh auth refresh failed. try running 'gh auth login' manually."
fi

step "logging into ghcr.io as ${GH_USER}…"
gh auth token | docker login ghcr.io -u "$GH_USER" --password-stdin >/dev/null 2>&1 \
  || fail "docker login failed. try 'gh auth refresh -s read:packages' and re-run."

# ─── Setup install dir ────────────────────────────────────────────────────────
echo
if [ -d "$INSTALL_DIR" ]; then
  warn "directory $INSTALL_DIR already exists."
  ask "overwrite the docker-compose.yml + .env in there? (y/N):"
  read -r OVERWRITE
  if [[ ! "$OVERWRITE" =~ ^[Yy]$ ]]; then
    fail "aborted. either remove $INSTALL_DIR or set OPENMLC_DIR=/some/other/path and re-run."
  fi
fi

mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR"
step "using install dir: $INSTALL_DIR"

# ─── Download compose + env template ──────────────────────────────────────────
step "downloading docker-compose.yml…"
curl -sSL -o docker-compose.yml "$REPO_RAW/docker-compose.yml" \
  || fail "could not download docker-compose.yml from $REPO_RAW"

# ─── Generate .env with fresh secrets ─────────────────────────────────────────
step "generating session + encryption secrets…"
SESSION_SECRET=$(openssl rand -hex 32)
ENCRYPTION_KEY=$(openssl rand -hex 32)

cat > .env <<EOF
# Generated by install.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# DO NOT commit this file. Keep these secrets private.

SESSION_SECRET=${SESSION_SECRET}
ENCRYPTION_KEY=${ENCRYPTION_KEY}

# Optional — pre-fill provider API keys, or paste them in /settings/api-keys after first run.
# OPENAI_API_KEY=
# ANTHROPIC_API_KEY=
# OPENROUTER_API_KEY=
# GOOGLE_API_KEY=
# XAI_API_KEY=
# FIREWORKS_API_KEY=

# Optional — bearer token for the OpenAI-compat /v1/chat/completions endpoint.
# OPENMLC_API_KEY=
EOF

chmod 600 .env
step "wrote .env (mode 0600)"

# ─── Pull + start ─────────────────────────────────────────────────────────────
step "pulling image (first run can take a minute)…"
docker compose pull >/dev/null 2>&1 || fail "image pull failed. is your token valid + does your account have access to the package?"

step "starting openmlc…"
docker compose up -d >/dev/null 2>&1 || fail "docker compose up failed. run \`docker compose logs\` in $INSTALL_DIR to see why."

# ─── Wait for healthcheck ────────────────────────────────────────────────────
step "waiting for the server to come up…"
for i in {1..30}; do
  if curl -fs -o /dev/null http://localhost:3000/api/models 2>/dev/null; then
    READY=1
    break
  fi
  sleep 1
done

echo
if [ "${READY:-0}" = "1" ]; then
  printf "${GREEN}${BOLD}✓ openmlc is live${NC}\n"
  echo
  printf "  ${BOLD}→${NC} open ${BOLD}http://localhost:3000${NC} in your browser\n"
  echo
  printf "  ${DIM}install dir:    ${NC}$INSTALL_DIR\n"
  printf "  ${DIM}view logs:      ${NC}cd $INSTALL_DIR && docker compose logs -f\n"
  printf "  ${DIM}stop:           ${NC}cd $INSTALL_DIR && docker compose down\n"
  printf "  ${DIM}update:         ${NC}cd $INSTALL_DIR && docker compose pull && docker compose up -d\n"
  echo
  printf "  ${DIM}your data lives in named docker volumes (openmlc-data + openmlc-uploads).${NC}\n"
  printf "  ${DIM}don't run 'docker compose down -v' — that wipes them.${NC}\n"
  echo
else
  warn "container started but the server didn't respond on :3000 in 30s."
  warn "check logs with: cd $INSTALL_DIR && docker compose logs -f"
fi
